name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [python, javascript, java]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to use a newer version

    - name: Set up ${{ matrix.language }} environment
      if: matrix.language == 'python'
      uses: actions/setup-python@v4  # Updated to use a newer version
      with:
        python-version: '3.x'
    
    - name: Set up ${{ matrix.language }} environment
      if: matrix.language == 'javascript'
      uses: actions/setup-node@v3  # Updated to use a newer version
      with:
        node-version: '16'
    
    - name: Set up ${{ matrix.language }} environment
      if: matrix.language == 'java'
      uses: actions/setup-java@v3  # Updated to use a newer version
      with:
        java-version: '11'
        distribution: 'adopt'  # Specify the distribution for Java

    - name: Install dependencies for Python
      if: matrix.language == 'python'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install dependencies for JavaScript
      if: matrix.language == 'javascript'
      run: npm install

    - name: Install dependencies for Java
      if: matrix.language == 'java'
      run: ./gradlew build

    - name: Run tests for Python
      if: matrix.language == 'python'
      run: python -m unittest discover

    - name: Run tests for JavaScript
      if: matrix.language == 'javascript'
      run: npm test

    - name: Run tests for Java
      if: matrix.language == 'java'
      run: ./gradlew test

    - name: Notify failure
      if: failure()
      run: echo "There are errors in the code. Please check the logs."
