name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [python, javascript, java]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up ${{ matrix.language }}
      if: matrix.language == 'python'
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Set up ${{ matrix.language }}
      if: matrix.language == 'javascript'
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Set up ${{ matrix.language }}
      if: matrix.language == 'java'
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install dependencies
      if: matrix.language == 'python'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install dependencies
      if: matrix.language == 'javascript'
      run: npm install

    - name: Install dependencies
      if: matrix.language == 'java'
      run: |
        ./gradlew build
        ./gradlew test

    - name: Run tests
      if: matrix.language == 'python'
      run: python -m unittest discover

    - name: Run tests
      if: matrix.language == 'javascript'
      run: npm test

    - name: Run tests
      if: matrix.language == 'java'
      run: ./gradlew test

    - name: Notify failure
      if: failure()
      run: echo "There are errors in the code. Please check the logs."
