name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2

      - name: Configure Poetry for a local virtual environment
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - name: Define cache for Poetry virtual environment
        uses: actions/cache@v3
        with:
          path: FileFinder_19/.venv
          key: venv-${{ hashFiles('FileFinder_19/poetry.lock') }}
          restore-keys: |
            venv-

      - name: Install project dependencies
        run: |
          cd FileFinder_19
          poetry install

      - name: Run Python Scripts
        run: |
          cd FileFinder_19
          poetry run python file_info_mapfolders.py
          poetry run python file_info_version_22.py
          poetry run python machine_info_migration_centre.py

      - name: Run PowerShell Script
        run: pwsh ./PowerShell/PS__ArunV2_Final_8Feb2024.ps1

      - name: Install MySQL Client
        run: choco install mysql

      - name: Run SQL Scripts
        run: |
          mysql -h ${{ secrets.MYSQL_HOST }} -P ${{ secrets.MYSQL_PORT }} \
          -u ${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_PASSWORD }} \
          ${{ secrets.MYSQL_DATABASE }} < SQLScripts/lisney_files_info8_bp_14Feb2024.sql
          
          mysql -h ${{ secrets.MYSQL_HOST }} -P ${{ secrets.MYSQL_PORT }} \
          -u ${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_PASSWORD }} \
          ${{ secrets.MYSQL_DATABASE }} < SQLScripts/sql_Cased_Dimensions14Jan2024_v2.sql

      - name: Upload CSV file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: file-type-counts
          path: FileTypeCounts_*.csv
